kind: dataset/stream/multimodal
name: atr01-iot
mdetadata:
  labels:
    app: openpack-benchmarks
    version: 1.0.0
    multimodal: true
spec:
  imu:
    kind: dataset/stream/imu
    path:
      dir: ${path.openpack.rootdir}/${user.name}/window
      fname: ${session}.npz
      full_path: ${.dir}/${.fname}