seed: 10
defaults:
  - common
  - path
  - dataset/stream: atr01-iot
  - dataset/stream_k4a: k4a-2d-kpt
  - dataset/split: pilot-challenge
  - optimizer: adam-exp
  - model: dcl
  - _self_
  - override hydra/job_logging: custom
metadata:
  task: ${dataset.annotation.name}
  labels:
    app: openpack-benchmarks
    issue: "I01-EXP01-V1"
    params: "${optimizer.name}/LR${optimizer.lr}"
train:
  epochs:
    minimum: 100
    maximum: 500
  checkpoint: last
  early_stop:
    monitor: "train_acc"
    min_delta: 0.001
    patience: 30
    verbose: false
    mode: "max"
