assistant_ckpt_path: "/datastore/code/U0105.ckpt"    ##change here for the assistan model ckpt path
logdir: "/datastore/code/log/student/U0105"     ##change here for the log dir path
teacher_pt_path: "/datastore/saved_model/openpack_stgcn.pt"   ##change here for the teacher model pt path
defaults:
  - common
  - _self_
  - override hydra/job_logging: custom

train:
  checkpoint: last
  early_stop:
    monitor: "train_acc"
    min_delta: 0.001
    patience: 30
    verbose: false
    mode: "max"

dataset:
  path: data/${user.name}/window/${session}.npz     ## change here for the dataset path
  split:
    name: U0105
    train:
      - [U0101, S0100]
      - [U0102, S0100]
      - [U0103, S0100]
      - [U0104, S0100]
      - [U0106, S0100]
      - [U0107, S0100]
      - [U0108, S0100]
      - [U0109, S0100]
      - [U0110, S0100]
      - [U0111, S0100]
      - [U0101, S0700]     ##virtual imu data
    val:
      - [U0101, S0600]
      
    test:
      - [U0105, S0100]
      - [U0105, S0200]
      - [U0105, S0300]
      - [U0105, S0400]
      - [U0105, S0500]

      - [U0202, S0100]
      - [U0202, S0200]
      - [U0202, S0300]
      - [U0202, S0400]
      - [U0202, S0500]