assistant_ckpt_path: "${path}/saved_model/model/assistant/work_dep/work_dep_assistant_without_DA.ckpt"    ##change here for the assistan model ckpt path

defaults:
  - common
  - path
  - _self_
  - override hydra/job_logging: custom


train:
  checkpoint: last
  early_stop:
    monitor: "train_acc"
    min_delta: 0.001
    patience: 30
    verbose: false
    mode: "max"

dataset:
  split:
    name: worker_dependent
    train:
      - [U0101, S0100]
      - [U0102, S0100]
      - [U0103, S0100]
      - [U0104, S0100]
      - [U0105, S0100]
      - [U0106, S0100]
      - [U0107, S0100]
      - [U0108, S0100]
      - [U0109, S0100]
      - [U0110, S0100]
      - [U0111, S0100]
    val:
      - [U0101, S0600]
    test:
      - [U0101, S0200]
      - [U0101, S0300]
      - [U0101, S0400]
      - [U0101, S0500]

      - [U0102, S0200]
      - [U0102, S0300]
      - [U0102, S0400]
      - [U0102, S0500]

      - [U0103, S0200]
      - [U0103, S0300]
      - [U0103, S0400]
      - [U0103, S0500]

      - [U0104, S0200]
      - [U0104, S0300]
      - [U0104, S0400]

      - [U0105, S0200]
      - [U0105, S0300]
      - [U0105, S0400]
      - [U0105, S0500]

      - [U0106, S0200]
      - [U0106, S0300]
      - [U0106, S0400]
      - [U0106, S0500]

      - [U0107, S0200]
      - [U0107, S0300]
      - [U0107, S0400]
      - [U0107, S0500]

      - [U0108, S0200]
      - [U0108, S0300]
      - [U0108, S0500]

      - [U0109, S0200]
      - [U0109, S0300]
      - [U0109, S0400]
      - [U0109, S0500]

      - [U0110, S0200]
      - [U0110, S0300]
      - [U0110, S0400]
      - [U0110, S0500]

      - [U0111, S0200]
      - [U0111, S0300]
      - [U0111, S0400]
      - [U0111, S0500]

      - [U0201, S0300]
      - [U0201, S0400]
      - [U0201, S0500]

      - [U0202, S0100]
      - [U0202, S0200]
      - [U0202, S0300]
      - [U0202, S0400]
      - [U0202, S0500]

      - [U0203, S0100]
      - [U0203, S0200]
      - [U0203, S0300]
      - [U0203, S0400]
      - [U0203, S0500]

      - [U0204, S0100]
      - [U0204, S0200]
      - [U0204, S0300]
      - [U0204, S0400]
      - [U0204, S0500]

      - [U0205, S0100]
      - [U0205, S0200]
      - [U0205, S0300]
      - [U0205, S0400]
      - [U0205, S0500]

      - [U0206, S0100]
      - [U0206, S0200]
      - [U0206, S0300]
      - [U0206, S0400]
      - [U0206, S0500]

      - [U0207, S0100]
      - [U0207, S0200]
      - [U0207, S0300]
      - [U0207, S0400]
      - [U0207, S0500]

      - [U0208, S0100]
      - [U0208, S0200]
      - [U0208, S0300]
      - [U0208, S0400]
      - [U0208, S0500]

      - [U0209, S0100]
      - [U0209, S0200]
      - [U0209, S0300]
      - [U0209, S0400]
      - [U0209, S0500]

      - [U0210, S0100]
      - [U0210, S0200]
      - [U0210, S0300]
      - [U0210, S0400]
      - [U0210, S0500]