path: "/datastore/TAL_research-main" ## change here for the code base path
teacher_pt_path: "${path}/saved_model/teacher/openpack_stgcn.pt"   ##change here for the teacher model pt path
logdir: "${path}/log/student/work_dep1"  ##change here for the log dir path
dataset:
  path:  ${path}/data/${user.name}/window/${session}.npz ## change here for the dataset path